Add --jit flag to Benchmarker
Samsung/walrus pull request #178
Opened 2023-10-10 09:18 UTC by GorogPeter

2023-11-02 01:08 UTC, clover2123 commented
Please rebase this patch based on the main branch

2023-11-02 17:54 UTC, zherczeg requested changes

2023-11-02 17:54 UTC, zherczeg commented on test/wasmBenchmarker/benchmark.py
> +    flags = "--jit --run-export runtime" if jit else "--run-export runtime"
This is a string duplication. Maybe this work:
`"--run-export runtime" + (" --jit" if jit else "")`

2023-11-04 04:27 UTC, zherczeg commented on test/wasmBenchmarker/benchmark.py
> +def measure_time(path, name, functon, engine=None, jit=False):
This is not introduced here, but `functon` should be changed to `function`. Otherwise the patch ok.

2023-11-07 05:35 UTC, zherczeg approved these changes
LGTM

2023-11-09 06:28 UTC, clover2123 approved these changes

2023-11-09 06:29 UTC, merged