Fix unaligned memory access in Interp on ARM32
Samsung/walrus pull request #226
Opened 2024-02-05 12:54 UTC by GorogPeter

Walrus Interp uses reinterpret_cast for data movement in load and store instructions. On ARM32, if the size of the data to be moved is 8 bytes, then compiler generates LDRD and STRD instructions. Address for these instructions has to be word-aligned, whilst Walrus has to support non-aligned data movement.

To achieve this, Walrus now uses memcpyEndianAware function for moving 8 byte-long data (int64, uint64 and double) in Interp on ARM32. This function generates two LDR and two STR instructions that can cope with non-aligned addresses.

Moreover, memory.wast test has been improved in order to check unaligned memory access.

Unfortunately Qemu-arm doesn't care about memory alignment, therefor it won't cause BUS ERROR (but it does occure on arm hardware).

2024-02-05 14:16 UTC, zherczeg requested changes

2024-02-05 14:16 UTC, zherczeg commented on src/runtime/Memory.h
> +
Remove this newline.

2024-02-05 14:16 UTC, zherczeg commented on src/runtime/Memory.h
> +#define createAlignmentSafeLoad(TYPE)                                                          \
defineUnalignedLoad / defineUnalignedStore

2024-02-05 14:16 UTC, zherczeg commented on src/runtime/Memory.h
> +#undef createAlignmentSafeLoad
incorrect undef

2024-02-06 09:12 UTC, zherczeg requested changes

2024-02-06 09:12 UTC, zherczeg commented on test/basic/memory.wast
> +;; memory is 4 kilobyte aligned, therefore index 1 will not be four byte aligned.
64 KB aligned

2024-02-06 09:12 UTC, zherczeg commented on test/basic/memory.wast
> +(assert_return (invoke "storeInt64" (i32.const 0x1) (i64.const 0x0123456789abcdef)))
There should be a loadInt8 check as well, which checks that the last byte is really written on offset 1. On earlier ARMs, the lower bits of the offsets were ignored, so this test could pass even if the code does not work.

2024-02-10 12:12 UTC, GorogPeter commented
Don't merge!
I've found some errors.

2024-02-12 11:42 UTC, GorogPeter commented
Nevermind. Problem solved. (It was a local problem.)

2024-02-13 09:08 UTC, merged