Improve CI
Samsung/walrus pull request #281
Opened 2024-08-05 09:45 UTC by vorosl

Test with jit-no-reg-alloc

2024-08-06 04:42 UTC, clover2123 commented
Is there any reason to maintain `no-register-allocation` mode?
It seems that register allocation is fully applied.

2024-08-06 04:57 UTC, zherczeg commented
It is purely for debugging purposes. It tests memory arguments for operations. We can close the bug (or reduce tests) if it is not necessary. Especially if it increases the CI time.

2024-08-06 05:03 UTC, zherczeg commented on .github/workflows/actions.yml
> +        $RUNNER --no-reg-alloc --engine="$GITHUB_WORKSPACE/out/clang/x64/walrus"
`--no-reg-alloc` also enables `--jit`?

2024-08-06 05:03 UTC, clover2123 commented on .github/workflows/actions.yml
> +        $RUNNER --no-reg-alloc --engine="$GITHUB_WORKSPACE/out/pure/x86/walrus" basic-tests wasm-test-core jit
The number of build options increased a lot and seems quite complex.
What about utilizing `matrix` feature of actions to run each test simply?
(reference of matrix: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-a-matrix-for-your-jobs)

2024-08-06 09:47 UTC, vorosl commented on .github/workflows/actions.yml
> +        $RUNNER --no-reg-alloc --engine="$GITHUB_WORKSPACE/out/clang/x64/walrus"
Yes

2024-08-21 11:04 UTC, zherczeg requested changes
Only one change.

2024-08-21 11:04 UTC, zherczeg commented on tools/run-tests.py
> +    parser.add_argument('--no-reg-alloc', action='store_true', help='test with JIT without register allocation')
`--jit-no-reg-alloc`

2025-02-25 10:29 UTC, zherczeg commented
82 tests are a lot of. I don't know if we have a quota

2025-02-25 10:47 UTC, vorosl commented
> 82 tests are a lot of. I don't know if we have a quota

https://docs.github.com/en/actions/administering-github-actions/usage-limits-billing-and-administration#about-billing-for-github-actions

> GitHub Actions usage is free for standard GitHub-hosted runners in public repositories, and for self-hosted runners.

I think these tests are well-separated. It doesn't test interpreter and jit in one test. With this approach it is easier to determine the failure from the titles of tests.

2025-03-03 07:55 UTC, zherczeg approved these changes
LGTM

2025-03-03 09:35 UTC, merged