WASI: add args_get and args_sizes_get
Samsung/walrus pull request #308
Opened 2024-11-21 15:24 UTC by matetokodi

WASI: add args_get and args_sizes_get
Extend testing script for passing arguments.

Depends on https://github.com/Samsung/walrus/pull/307 and https://github.com/Samsung/walrus/pull/309

2024-11-22 07:35 UTC, zherczeg commented on src/wasi/WASI.cpp
> +    char** uvArgv = reinterpret_cast<char**>(get_memory_pointer(instance, argv[0], argc * sizeof(char*)));
I don't think this is correct. char* pointers can be 32 or 64 bit long depending on the cpu, while the output is 32 bit long offsets.

2024-11-22 07:56 UTC, zherczeg commented on src/wasi/WASI.cpp
> +    char** uvArgv = reinterpret_cast<char**>(get_memory_pointer(instance, argv[0], argc * sizeof(char*)));
I have created a `TemporaryData` class in the #307 patch which should help.

2024-11-26 00:40 UTC, clover2123 commented
Please rebase this patch

2024-11-27 07:39 UTC, zherczeg requested changes

2024-11-27 07:39 UTC, zherczeg commented on src/shell/Shell.cpp
> +int main(const int argc, const char* argv[])
for an `int` const is pointless.

2024-11-27 07:39 UTC, zherczeg commented on src/wasi/WASI.h
> +    F(args_get, I32I32_RI32)                       \
Order here as well.

2024-12-02 09:12 UTC, matetokodi commented on src/wasi/WASI.cpp
> +void WASI::args_get(ExecutionState& state, Value* argv, Value* result, Instance* instance)
As far as I can tell uvwasi sorts the functions alphabetically; But the order we have them in already is not alphabetical. Would you want me to sort the existing ones as well, or to just put the new args functions at the top?

2024-12-03 04:58 UTC, clover2123 commented on tools/run-tests.py
> +@runner('wasi-args', default=True)
What about merging this `wasi-args` runner into `wasi` test runner?

2024-12-03 10:38 UTC, zherczeg commented
#309 should land first.

2024-12-03 10:42 UTC, zherczeg commented on tools/run-tests.py
> +        subprocess_args = [engine, "--mapdirs", "./test/wasi", "/var"]
I realized this is a bad idea because stdout is cluttered with debug output.

2024-12-09 10:49 UTC, zherczeg requested changes
Nice patch!

2024-12-09 10:49 UTC, zherczeg commented on src/shell/Shell.cpp
> +                        fprintf(stderr, "error: --args requires an argument\n");
comment: `requires an argument list`, or `requires one or more arguments`

2024-12-09 10:49 UTC, zherczeg commented on test/wasi/args.wast
> +    drop
could we throw an error on nonzero return code? If you pass a buffer outside the memory area, it should throw error.

2024-12-09 10:49 UTC, zherczeg commented on test/wasi/args.wast
> +  (export "memory" (memory 0))
Why this needs to be exported? `(memory 1 1)` creates a 64K buffer.

2024-12-09 10:49 UTC, zherczeg commented on test/wasi/args.wast
> +  (data (i32.const 32) "Hello" ) ;; Memory[32] = "Hello,"
`Hello` or `Hello,`

2024-12-09 10:49 UTC, zherczeg commented on test/wasi/args.wast
> +    i32.const 1  ;; start at 1, skip argv[0] (name of currently running file)
Since the function returns with two buffers in an expected layout, we could check them in one step (without a loop for arguments).

2024-12-10 05:02 UTC, clover2123 approved these changes

2024-12-10 05:03 UTC, merged