Add Single Operand Instructions
Samsung/walrus pull request #39
Opened 2022-12-08 13:53 UTC by kulcsaradam

Extend instructions with single operand (op1) instructions.

Singed-off-by: Adam Laszlo Kulcsar kuladam@inf.u-szeged.hu

2022-12-13 10:44 UTC, zherczeg requested changes

2022-12-13 10:44 UTC, zherczeg commented on third_party/wabt/src/interp/jit/jit-backend.cc
> +  // source registers are not supported
Use full sentences (add a stop after the end)

2022-12-13 10:44 UTC, zherczeg commented on third_party/wabt/src/interp/jit/jit-backend.cc
> +  sljit_emit_op1(compiler, mov, SLJIT_R0, 0, args[0].arg, args[0].argw);
Only needed for immediate operands. I.e: args[0].arg & SLJIT_IMM is true.

2022-12-13 10:44 UTC, zherczeg commented on third_party/wabt/src/interp/jit/jit-backend.cc
> +  sljit_s32 mov = SLJIT_MOV;
Only needed when mov is needed.

Btw: for immedates the result is a constant. This could be computed ahead and use a simple mov.

2022-12-13 11:30 UTC, zherczeg commented on third_party/wabt/src/interp/jit/jit-backend.cc
> +  sljit_emit_op1(compiler, mov, SLJIT_R0, 0, args[0].arg, args[0].argw);
You can keep it, it is non-tirival.

2022-12-13 11:32 UTC, zherczeg commented on third_party/wabt/src/interp/jit/jit-backend.cc
> +    sljit_emit_op1(compiler, opcode, args[1].arg, args[1].argw, SLJIT_R0, 0);
Trick:
set `args[1].arg = SLJIT_R0` and `args[1].argw = 0` and use the generic case. Less code is generated then.

2022-12-13 13:41 UTC, zherczeg commented on third_party/wabt/src/interp/jit/jit-backend.cc
> +    sljit_emit_op1(compiler, SLJIT_MOV, SLJIT_R0, 0, args[0].arg, args[0].argw);
MOV, MOV32 still needed :)

2022-12-19 10:14 UTC, kulcsaradam commented
Requested changes should be done. Also changed the commit to **Implement Unary Instructions** for clarity.

2022-12-19 10:31 UTC, zherczeg approved these changes
LGTM

2022-12-19 10:31 UTC, merged