Fix style issues after integration
Samsung/walrus pull request #70
Opened 2023-02-16 08:34 UTC by kulcsaradam

2023-02-16 11:42 UTC, zherczeg requested changes
Looks better! I would keep the defines and one-statement functions

2023-02-16 11:42 UTC, zherczeg commented on src/jit/Backend.cpp
> +#define OffsetOfContextField(field) (static_cast<sljit_sw>(offsetof(ExecutionContext, field)) - static_cast<sljit_sw>(sizeof(ExecutionContext)))
Should keep the original

2023-02-16 11:42 UTC, zherczeg commented on src/jit/Backend.cpp
> +#define GET_TARGET_REG(arg, default_reg) (((arg)&SLJIT_MEM) ? (default_reg) : (arg))
I would not change the defines.

2023-02-16 11:42 UTC, zherczeg commented on src/jit/FloatMathInl.h
> +static sljit_f32 floatNearest(sljit_f32 val) { return std::nearbyint(val); }
I think the original form is preferred for these

2023-02-22 11:27 UTC, zherczeg requested changes
Quite good! The main problem is merging single line functions.

2023-02-22 11:27 UTC, zherczeg commented on src/jit/Backend.cpp
> +#define GET_SOURCE_REG(arg, default_reg) (IS_SOURCE_REG(arg) ? (arg) : (default_reg))
I would keep the original

2023-02-22 11:27 UTC, zherczeg commented on src/jit/FloatMathInl.h
> +static sljit_f64 floatCopySign(sljit_f64 lhs, sljit_f64 rhs) { return std::copysign(lhs, rhs); }
I would keep these two

2023-02-22 11:27 UTC, zherczeg commented on src/jit/InstList.cpp
> +ComplexInstruction::~ComplexInstruction() { delete[] params(); }
I would keep these two as well, one liner functions should be merged only in classes for getters / setter.

2023-02-22 11:27 UTC, zherczeg commented on src/runtime/Module.h
> +#endif // __WalrusModule__
Don't remove this line

2023-02-22 13:10 UTC, clover2123 commented
[FYI] In `interp` branch, we use clang-format-10 for code format checker.
We run the following command to check the code format
```sh
tools/check_tidy.py
```

2023-02-22 13:28 UTC, zherczeg commented
Unfortunately it does not check line breaks and invalid variable namings :(

2023-02-24 11:11 UTC, zherczeg requested changes
Good progress. Only one change remained.

2023-02-24 11:11 UTC, zherczeg commented on src/jit/Locals.cpp
> +    bool operator<(const LocalRange& other) const { return (start < other.start); }
Revert this.

2023-02-24 12:24 UTC, kulcsaradam commented on src/jit/Locals.cpp
> +    bool operator<(const LocalRange& other) const { return (start < other.start); }
It should be done.

2023-02-27 10:28 UTC, zherczeg approved these changes
LGTM

2023-02-27 10:28 UTC, merged